<?php

$modversion['name'] = BBOARD_NAME;
$modversion['version'] = '1.13';
$modversion['description'] = BBOARD_DESC;
$modversion['credits'] = 'Made by<br>Koudanshi<br>( http://www.koudanshi.net/ )';
$modversion['author'] = 'Koudanshi';
$modversion['help'] = 'None';
$modversion['license'] = 'Please read the licence carefully, PHPBB Groups will not have any responsibility for problems/troubles you encounter when use this PHPBB module.';
$modversion['license'] .= "Please don't contact PHPBB Group for any problems which cause by use this module because they will not support you any things.";
$modversion['official'] = 0;
$modversion['image'] = './images/logo.gif';
$modversion['dirname'] = 'pbboard';
// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
$modversion['dropsqlfile']['mysql'] = 'sql/dropmysql.sql';
//---------------------------------------------
// Tables created by sql file (without prefix!)
//---------------------------------------------
$modversion['tables'][1] = 'pbb_confirm';
$modversion['tables'][2] = 'pbb_auth_access';
$modversion['tables'][3] = 'pbb_user_group';
$modversion['tables'][4] = 'pbb_groups';
$modversion['tables'][5] = 'pbb_banlist';
$modversion['tables'][6] = 'pbb_categories';
$modversion['tables'][7] = 'pbb_config';
$modversion['tables'][8] = 'pbb_disallow';
$modversion['tables'][9] = 'pbb_forum_prune';
$modversion['tables'][10] = 'pbb_forums';
$modversion['tables'][11] = 'pbb_posts';
$modversion['tables'][12] = 'pbb_posts_text';
$modversion['tables'][13] = 'pbb_privmsgs';
$modversion['tables'][14] = 'pbb_privmsgs_text';
$modversion['tables'][15] = 'pbb_search_results';
$modversion['tables'][16] = 'pbb_search_wordlist';
$modversion['tables'][17] = 'pbb_search_wordmatch';
$modversion['tables'][18] = 'pbb_themes';
$modversion['tables'][19] = 'pbb_themes_name';
$modversion['tables'][20] = 'pbb_topics';
$modversion['tables'][21] = 'pbb_topics_watch';
$modversion['tables'][22] = 'pbb_vote_desc';
$modversion['tables'][23] = 'pbb_vote_results';
$modversion['tables'][24] = 'pbb_vote_voters';
$modversion['tables'][25] = 'pbb_words';
$modversion['tables'][26] = 'pbb_attachments_config';
$modversion['tables'][27] = 'pbb_forbidden_extensions';
$modversion['tables'][28] = 'pbb_extension_groups';
$modversion['tables'][29] = 'pbb_extensions';
$modversion['tables'][30] = 'pbb_attachments_desc';
$modversion['tables'][31] = 'pbb_attachments';
$modversion['tables'][32] = 'pbb_quota_limits';
$modversion['tables'][33] = 'pbb_attach_quota';
//--------------
// Admin things
//--------------
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'index.php';
$modversion['adminmenu'] = 'menu.php';
// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = 'search.inc.php';
$modversion['search']['func'] = 'pbboard_search';
// Menu
$modversion['hasMain'] = 1;
// Blocks
$modversion['blocks'][1]['file'] = 'pbboard.php';
$modversion['blocks'][1]['name'] = BBOARD_BNAME1;
$modversion['blocks'][1]['description'] = 'Shows recent topics in the forums';
$modversion['blocks'][1]['show_func'] = 'pbboard_show';
$modversion['blocks'][1]['options'] = '10|1|time';
$modversion['blocks'][1]['edit_func'] = 'pbboard_edit';
$modversion['blocks'][1]['template'] = 'pbboard_block_new.html';
$modversion['blocks'][2]['file'] = 'pbboard.php';
$modversion['blocks'][2]['name'] = BBOARD_BNAME2;
$modversion['blocks'][2]['description'] = 'Shows most viewed topics in the forums';
$modversion['blocks'][2]['show_func'] = 'pbboard_show';
$modversion['blocks'][2]['options'] = '10|1|views';
$modversion['blocks'][2]['edit_func'] = 'pbboard_edit';
$modversion['blocks'][2]['template'] = 'pbboard_block_top.html';
$modversion['blocks'][3]['file'] = 'pbboard.php';
$modversion['blocks'][3]['name'] = BBOARD_BNAME3;
$modversion['blocks'][3]['description'] = 'Shows most active topics in the forums';
$modversion['blocks'][3]['show_func'] = 'pbboard_show';
$modversion['blocks'][3]['options'] = '10|1|replies';
$modversion['blocks'][3]['edit_func'] = 'pbboard_edit';
$modversion['blocks'][3]['template'] = 'pbboard_block_active.html';
// Smarty
$modversion['use_smarty'] = 1;
